name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Verify Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          
      - name: Install dependencies
        working-directory: WikiLinkVerification.Web
        run: npm install

      - name: Build and Publish
        run: |
          echo "Building from directory:"
          pwd
          dotnet publish WikiLinkVerification.Web/WikiLinkVerification.Web.csproj -c Release -o release --nologo
          
      - name: Change base-tag in index.html
        run: |
          index=release/wwwroot/index.html
          sed -i 's/<base href="\/"/<base href="\/"/g' $index
          
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages