name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: List directory contents for debugging
        run: ls -la
          
      - name: Install dependencies
        run: |
          cd WikiLinkVerification.Web
          npm install

      # Removed working-directory and use explicit paths
      - name: Publish
        run: |
          dotnet workload restore
          dotnet publish $(pwd)/WikiLinkVerification.Web/WikiLinkVerification.Web.csproj -c Release -o release --nologo
          
      - name: Change base-tag in index.html
        run: |
          index=release/wwwroot/index.html
          sed -i 's/<base href="\/"/<base href="\/"/g' $index
          
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages